### ISSUE TITLE
Question on test `affine_loop_unroll.mlir`

### ISSUE THREAD

**Issue by vguerra** [j2kun/mlir-tutorial#13]
Specifically regarding the test on function `@test_doubly_nested_loop`: should line [23](https://github.com/j2kun/mlir-tutorial/blob/main/tests/affine_loop_unroll.mlir#L23) be as well preceded by a `// CHECK-NOT: affine.for`? IIUC, the point of the test is to make sure that nested instances of `affine.for` are as well transformed or it is not really necessary?

**Comment by j2kun** [comment]
In this case, FileCheck will match any line in the output for that check, so it would catch inner nested loops as well. FileCheck is a "dumb" regex tool, so it doesn't know anything about the syntax of the input.

I think what is really missing here is something that splits the test on line [7](https://github.com/j2kun/mlir-tutorial/blob/main/tests/affine_loop_unroll.mlir#L7) from the test on line [18](https://github.com/j2kun/mlir-tutorial/blob/main/tests/affine_loop_unroll.mlir#L18), since the `// CHECK-NOT: affine.for` technically would match across those. Otherwise if the second test input produced a `for` in its output, the first `CHECK-NOT` would fail. A minor issue, but a "better" practice.

The way around it is to add a line `// CHECK-LABEL: <test_name>` just before each test, which would cause the first `CHECK-NOT` to check lines before the label, and the second for the lines after the label.

But I'm on vacation in Hawaii right now, so I will do this next week. Aloha! 😄

**Comment by vguerra** [comment]
Thank you for taking the time to comment and explain. I got it now. As well, I took the liberty to push a PR https://github.com/j2kun/mlir-tutorial/pull/14 that simply adds those `CHECK-LABEL` directives 😀.

Enjoy Hawaii 🌴 🏄🏻‍♂️ 🌊

**Comment by j2kun** [comment]
Thanks!
